bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': '$100,000',
    '200000': '$200,000',
    '300000': '$300,000',
    '400000': '$400,000',
    '500000': '$500,000',
    '600000': '$600,000',
    '700000': '$700,000',
    '800000': '$800,000',
    '900000': '$900,000',
    '1000000': '$1M+',
}

# zh
state_choices = {
    'HE': '河北省',
    'SX': '山西省',
    'LN': '辽宁省',
    'JL': '吉林省',
    'HLJ': '黑龙江省',
    'JS': '江苏省',
    'ZJ': '浙江省',
    'AH': '安徽省',
    'FJ': '福建省',
    'JX': '江西省',
    'SD': '山东省',
    'HA': '河南省',
    'HB': '湖北省',
    'GD': '广东省',
    'HN': '海南省',
    'SC': '四川省',
    'GZ': '贵州省',
    'YN': '云南省',
    'SN': '陕西省',
    'GS': '甘肃省',
    'QH': '青海省',
    'TW': '台湾省',
    'NMG': '内蒙古自治区',
    'GX': '广西壮族自治区',
    'XZ': '西藏自治区',
    'NX': '宁夏回族自治区',
    'XJ': '新疆维吾尔自治区',
    'HK': '香港特别行政区',
    'MACAU': '澳门特别行政区',
}

# en
# state_choices = {
#     'AK': 'Alaska',
#     'AL': 'Alabama',
#     'AR': 'Arkansas',
#     'AS': 'American Samoa',
#     'AZ': 'Arizona',
#     'CA': 'California',
#     'CO': 'Colorado',
#     'CT': 'Connecticut',
#     'DC': 'District of Columbis',
#     'DE': 'Delaware',
#     'FL': 'Florida',
#     'GA': 'Georgia',
#     'GU': 'Guam',
#     'HI': 'Hawaii',
#     'IA': 'Iowa',
#     'ID': 'Idaho',
#     'IL': 'Illinois',
#     'IN': 'Indiana',
#     'IA': 'Iowa',
#     'KS': 'Kansas',
#     'KY': 'Kentucky',
#     'LA': 'Louisiana',
#     'ME': 'Maine',
#     'MD': 'Maryland',
#     'MA': 'Massachusetts',
#     'MI': 'Michigan',
#     'MN': 'Minnesota',
#     'MS': 'Mississippi',
#     'MO': 'Missouri',
#     'MT': 'Montana',
#     'NE': 'Nebraska',
#     'NV': 'Nevada',
#     'NH': 'New Hampshire',
#     'NJ': 'New Jersey',
#     'NM': 'New Mexico',
#     'NY': 'New York',
#     'NC': 'North Carolina',
#     'ND': 'North Dakota',
#     'OH': 'Ohio',
#     'OK': 'Oklahoma',
#     'OR': 'Oregon',
#     'PA': 'Pennsylvania',
#     'RI': 'Rhode Island',
#     'SC': 'South Carolina',
#     'SD': 'South Dakota',
#     'TN': 'Tennessee',
#     'TX': 'Texas',
#     'UT': 'Utah',
#     'VT': 'Vermont',
#     'VA': 'Virginia',
#     'WA': 'Washington',
#     'WV': 'West Virginia',
#     'WI': 'Wisconsin',
#     'WY': 'Wyoming',
# }
